### ISSUE TITLE
Instructions on building?

### ISSUE THREAD

**Issue by scw** [travisdowns/avx-turbo#12]
Tried to compile on Mac OS and quickly realized that this was Linux only. The embedded `nasm` build doesn't seem to be used by default by the Makefile. I was able to run this in Linux container without issue once I had a Linux + nasm + gcc environment up.

**Comment by travisdowns** [comment]
@scw - yes, it is Linux only at the moment, I should make that clear! Thanks for your feedback.

In principle it could work on OSX and even Windows, but would need some porting (in particular, I would need to know the equivalent for the `rdmsr` calls which use the `msr` kernel module on Linux).

Let me check on the nasm thing.

**Comment by scw** [comment]
@travisdowns thanks for the fixes!
