### ISSUE TITLE
How to measure power consumption?

### ISSUE THREAD

**Issue by imaginary-person** [travisdowns/avx-turbo#19]
Hello Travis,

Have you ever measured power consumption of instructions running on a core? If so, how did/do you measure it?

**Comment by travisdowns** [comment]
@imaginary-person - you can do this with the RAPL counters. I don't have any public code handy, but it's fairly straightforward once you can read some MSRs. You can find a [good overview here](http://web.eece.maine.edu/~vweaver/projects/rapl/).

**Comment by imaginary-person** [comment]
Thank you! I guess I'll have to contend with RAPL, as I don't have physical access to the machine on which I wanted to measure power consumption, so I can't use a physical device.
